import Head from 'next/head';
import { motion } from 'framer-motion';

import styles from '../styles/Home.module.scss';

import Home from '../src/components/home/home';

export default function HomePage() {
  return (
    <motion.div 
      className={styles.container}
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
    >
      <Head>
        <title>Secure Call</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </motion.div>
  )
}
