export const tos = () => {
  return `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque elit eget gravida cum sociis natoque penatibus. Tempus urna et pharetra pharetra massa massa. Tellus at urna condimentum mattis pellentesque id nibh tortor id. Egestas erat imperdiet sed euismod. Proin nibh nisl condimentum id venenatis a condimentum vitae. Tellus in hac habitasse platea dictumst vestibulum rhoncus est. Sodales neque sodales ut etiam sit amet nisl. Adipiscing elit duis tristique sollicitudin. Justo nec ultrices dui sapien eget mi proin. Amet venenatis urna cursus eget nunc scelerisque viverra. Est lorem ipsum dolor sit. In fermentum et sollicitudin ac orci phasellus egestas tellus rutrum.
  
    Euismod in pellentesque massa placerat duis ultricies lacus sed turpis. Habitant morbi tristique senectus et netus et malesuada fames. Aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Nisi scelerisque eu ultrices vitae auctor eu. Sed adipiscing diam donec adipiscing tristique. Fermentum leo vel orci porta non pulvinar. Varius morbi enim nunc faucibus. Eu lobortis elementum nibh tellus. Neque volutpat ac tincidunt vitae semper quis lectus nulla at. Pellentesque habitant morbi tristique senectus et netus. Velit egestas dui id ornare. Eu feugiat pretium nibh ipsum consequat nisl vel pretium lectus.
    
    Et netus et malesuada fames ac turpis. Sed risus ultricies tristique nulla aliquet enim tortor at auctor. Risus nec feugiat in fermentum posuere urna. Sit amet nulla facilisi morbi tempus iaculis. Purus sit amet volutpat consequat mauris nunc. Commodo sed egestas egestas fringilla phasellus. Ac tincidunt vitae semper quis lectus nulla at volutpat diam. Id nibh tortor id aliquet lectus. Suspendisse in est ante in nibh mauris. Elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Eget velit aliquet sagittis id consectetur purus.
    
    In nibh mauris cursus mattis molestie a. Fermentum posuere urna nec tincidunt. In arcu cursus euismod quis viverra nibh. Sollicitudin ac orci phasellus egestas tellus rutrum. Egestas quis ipsum suspendisse ultrices gravida dictum. Orci porta non pulvinar neque laoreet. At augue eget arcu dictum varius duis at consectetur lorem. Sed turpis tincidunt id aliquet risus. Est velit egestas dui id ornare. Sollicitudin tempor id eu nisl nunc mi. Sed pulvinar proin gravida hendrerit. Egestas integer eget aliquet nibh. Iaculis urna id volutpat lacus laoreet non curabitur. Velit euismod in pellentesque massa. Lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit. Consectetur adipiscing elit pellentesque habitant. Metus aliquam eleifend mi in nulla posuere. Fringilla phasellus faucibus scelerisque eleifend donec. Luctus venenatis lectus magna fringilla urna porttitor rhoncus. Nunc pulvinar sapien et ligula.
    
    Gravida neque convallis a cras semper auctor. At varius vel pharetra vel. Enim sed faucibus turpis in eu mi bibendum neque. Erat nam at lectus urna duis convallis convallis. Morbi leo urna molestie at elementum eu. Volutpat maecenas volutpat blandit aliquam etiam erat velit scelerisque in. At consectetur lorem donec massa sapien faucibus et molestie ac. In est ante in nibh mauris cursus mattis molestie. Luctus venenatis lectus magna fringilla urna. Arcu dui vivamus arcu felis bibendum ut tristique. Nulla facilisi morbi tempus iaculis urna id volutpat lacus laoreet.
    
    Malesuada fames ac turpis egestas integer eget aliquet nibh praesent. Gravida in fermentum et sollicitudin ac orci. A cras semper auctor neque vitae tempus quam pellentesque. In tellus integer feugiat scelerisque varius morbi. Volutpat consequat mauris nunc congue nisi vitae suscipit tellus mauris. Sit amet venenatis urna cursus eget. Fusce ut placerat orci nulla pellentesque dignissim enim. Eget nunc scelerisque viverra mauris in aliquam. Amet risus nullam eget felis eget nunc lobortis. Massa tempor nec feugiat nisl. Pellentesque elit eget gravida cum sociis. Tortor at auctor urna nunc id cursus metus aliquam eleifend. Mauris pharetra et ultrices neque ornare aenean. Feugiat scelerisque varius morbi enim nunc. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at augue. Potenti nullam ac tortor vitae purus faucibus ornare. Tincidunt nunc pulvinar sapien et ligula. Convallis aenean et tortor at risus viverra adipiscing. Consectetur adipiscing elit ut aliquam purus. In nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque.
    
    Lacus sed viverra tellus in hac habitasse platea dictumst. Id volutpat lacus laoreet non curabitur. Est placerat in egestas erat. Mauris sit amet massa vitae. Sit amet luctus venenatis lectus magna fringilla. Vitae tempus quam pellentesque nec nam aliquam. Lorem ipsum dolor sit amet. Massa ultricies mi quis hendrerit dolor magna eget est lorem. Sapien faucibus et molestie ac. Lacinia at quis risus sed vulputate.
    
    Ac feugiat sed lectus vestibulum. Mi quis hendrerit dolor magna eget est. Lacus suspendisse faucibus interdum posuere. Turpis massa sed elementum tempus egestas sed sed risus pretium. Venenatis cras sed felis eget velit. Sapien et ligula ullamcorper malesuada. In vitae turpis massa sed elementum tempus egestas sed sed. Id eu nisl nunc mi ipsum faucibus vitae aliquet nec. Netus et malesuada fames ac turpis egestas sed tempus. Leo integer malesuada nunc vel risus commodo viverra.
    
    Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Quisque egestas diam in arcu cursus euismod. Sed odio morbi quis commodo odio. Orci sagittis eu volutpat odio facilisis mauris sit amet. Volutpat ac tincidunt vitae semper quis lectus nulla at volutpat. Nec nam aliquam sem et. Quisque non tellus orci ac auctor. Egestas pretium aenean pharetra magna ac placerat vestibulum lectus. Nulla facilisi morbi tempus iaculis urna id volutpat lacus. Accumsan sit amet nulla facilisi morbi tempus iaculis urna id. Vitae ultricies leo integer malesuada nunc. Pharetra magna ac placerat vestibulum lectus mauris. Sit amet nisl purus in mollis nunc.
    
    Egestas quis ipsum suspendisse ultrices. Justo laoreet sit amet cursus sit amet dictum sit. Dignissim enim sit amet venenatis urna cursus eget nunc scelerisque. Tellus id interdum velit laoreet id. Turpis massa sed elementum tempus. Sed pulvinar proin gravida hendrerit. Lacus vestibulum sed arcu non odio euismod lacinia at. Ut tristique et egestas quis. Tortor condimentum lacinia quis vel eros donec. Purus sit amet luctus venenatis lectus magna fringilla urna porttitor. Mattis enim ut tellus elementum sagittis vitae.
    
    In hac habitasse platea dictumst. Lacus luctus accumsan tortor posuere ac ut. Ultricies lacus sed turpis tincidunt id aliquet risus. Ac odio tempor orci dapibus ultrices in iaculis nunc sed. Ullamcorper malesuada proin libero nunc consequat interdum. Interdum consectetur libero id faucibus. Tortor posuere ac ut consequat semper viverra nam. Pharetra sit amet aliquam id diam. Donec enim diam vulputate ut pharetra. Felis eget velit aliquet sagittis id consectetur purus ut faucibus. Sed viverra tellus in hac habitasse platea. Integer enim neque volutpat ac.
    
    Molestie at elementum eu facilisis sed. Bibendum at varius vel pharetra vel. Blandit aliquam etiam erat velit scelerisque in dictum non. Morbi leo urna molestie at. Sit amet porttitor eget dolor morbi non. Vestibulum morbi blandit cursus risus at ultrices. Quisque non tellus orci ac auctor augue mauris. Mi tempus imperdiet nulla malesuada pellentesque elit eget gravida cum. Posuere urna nec tincidunt praesent semper feugiat. Donec adipiscing tristique risus nec feugiat in. Tortor id aliquet lectus proin nibh nisl condimentum. Eu non diam phasellus vestibulum. Dignissim diam quis enim lobortis. Amet nisl suscipit adipiscing bibendum est ultricies integer quis. Magna eget est lorem ipsum dolor. Eu nisl nunc mi ipsum. Ut etiam sit amet nisl purus. Amet aliquam id diam maecenas ultricies mi eget. Convallis aenean et tortor at risus.
    
    Aliquam id diam maecenas ultricies mi eget mauris pharetra. Mi bibendum neque egestas congue. Malesuada proin libero nunc consequat interdum varius sit. Etiam dignissim diam quis enim. At imperdiet dui accumsan sit amet nulla. Vel facilisis volutpat est velit egestas dui. A diam sollicitudin tempor id eu nisl nunc mi ipsum. Volutpat ac tincidunt vitae semper. Nulla pharetra diam sit amet nisl suscipit adipiscing bibendum. Massa ultricies mi quis hendrerit dolor magna eget. Adipiscing elit duis tristique sollicitudin nibh sit amet. Commodo nulla facilisi nullam vehicula ipsum a arcu cursus. Fermentum posuere urna nec tincidunt.
    
    Eget lorem dolor sed viverra. Nec ullamcorper sit amet risus nullam eget. Arcu vitae elementum curabitur vitae nunc sed. Aliquam purus sit amet luctus venenatis lectus magna fringilla. Sit amet aliquam id diam. Semper quis lectus nulla at. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Est lorem ipsum dolor sit amet consectetur adipiscing elit pellentesque. Turpis massa tincidunt dui ut ornare lectus sit amet. Scelerisque purus semper eget duis. Sed sed risus pretium quam. Sed lectus vestibulum mattis ullamcorper velit.
    
    Vivamus arcu felis bibendum ut tristique. Lobortis elementum nibh tellus molestie nunc non blandit. Habitant morbi tristique senectus et netus et. Quis risus sed vulputate odio ut enim. Cras sed felis eget velit. Vitae suscipit tellus mauris a diam maecenas sed. Hac habitasse platea dictumst quisque. Mi quis hendrerit dolor magna eget. Amet commodo nulla facilisi nullam vehicula ipsum. Sit amet nulla facilisi morbi tempus iaculis urna. Enim sit amet venenatis urna cursus. Quis hendrerit dolor magna eget est lorem. Diam quam nulla porttitor massa id neque aliquam vestibulum. Varius vel pharetra vel turpis nunc eget lorem dolor.`
}

export default tos;